Moto requires boto >= 2.33.0
Moto imports a class in boto that did not exist before boto 2.33.0

Partial traceback showing ImportError with versions of boto < 2.33.0:
  File "/src/python/moto/moto/__init__.py", line 8, in <module>
    from .autoscaling import mock_autoscaling  # flake8: noqa
  File "/src/python/moto/moto/autoscaling/__init__.py", line 2, in <module>
    from .models import autoscaling_backends
  File "/src/python/moto/moto/autoscaling/models.py", line 5, in <module>
    from moto.elb import elb_backends
  File "/src/python/moto/moto/elb/__init__.py", line 2, in <module>
    from .models import elb_backends
  File "/src/python/moto/moto/elb/models.py", line 4, in <module>
    from boto.ec2.elb.attributes import (
ImportError: cannot import name ConnectionSettingAttribute