Partial replacement of sure with regular assertions in sagemaker
The unit tests are failing in code that I did not change:

>       assert len(resp["ModelPackageSummaryList"]) == 1
E       assert 0 == 1
E        +  where 0 = len([])

tests/test_sagemaker/test_sagemaker_model_packages.py:61: AssertionError