Use new flake8 for Python 3.8 compatibility
With the current flake8, which depends on pyflakes<1.7.0,>=1.5.0,
linting fails with:

AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

The issue is fixed in pyflakes 2.1.0 [1]. Let's just use the latest
flake8.

[1] https://github.com/PyCQA/pyflakes/commit/7c74ab0ddccb60a9154c2af5aa4ee4581ccada4a