RDS: Fix `TypeError` when adding DBSnapshot/DBClusterSnapshot attribute values
Original code raises the following at runtime:

TypeError: unsupported operand type(s) for +: 'dict_values' and 'list'

This change coerces both values to `list` to allow the `+` operand to succeed.
It also changes the ordering so that any `values_to_add` are *appended* to the existing values

NOTE: These were the only two lines not covered by tests in #7232, and they both contained bugs!