Fix CloudFormation AWS::Logs::LogGroup tagging
CloudFormation AWS::Logs::LogGroup expects tags as an array of Tags:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

Whereas boto3's Logs `create_log_group()` expects tags to be a dict:

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs/client/create_log_group.html

So we need to transform how we provide tags to avoid getting:

```
E       AttributeError: 'list' object has no attribute 'items'
```